name: Final Cache Fix
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Cache
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: cache.txt
          key: cache-9958c9b

      - name: Create file if missing
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: echo "hello" > cache.txt

      - name: prime-cache-9958c9b
        run: echo "Done"
